theme: jekyll-theme-minimal
url: https://rnystrom.github.io/New-Awesome-Blog/
title: New Awesome Blog
subtitle: Stay tuned!
permalink: /blog/:year/:month/:day/:title/
baseurl: "" # the subpath of your site, e.g. /blog/
github_username: rnystrom
markdown: rdiscount
highlighter: pygments
paginate: 10
paginate_path: "/blog/:num/"
